[package]
name = "lidar-utils"
version = "0.8.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
description = "Utilities for Velodyne and Ouster LIDARs"
documentation = "https://docs.rs/lidar-utils/"
homepage = "https://github.com/jerry73204/rust-lidar-utils"
repository = "https://github.com/jerry73204/rust-lidar-utils"
readme = "README.md"
license = "MIT"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
serde-big-array = "0.3"
chrono = "0.4"
derivative = "2.1"
itertools = "0.10"
pcap = { version = "0.8", optional = true }
uom = { version = "0.31", features = ["si"] }
num-traits = "0.2"

[dev-dependencies]
log = "0.4"
pcap = "0.8"
toml = "0.5"

[features]
ouster-client-test = []
ouster-test = []
velodyne-test = []

[package.metadata.docs.rs]
features = ["pcap"]
no-default-features = true
