[package]
name = "lidar-utils"
version = "0.5.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
description = "Utilities for Velodyne and Ouster LIDARs"
documentation = "https://docs.rs/lidar-utils/"
homepage = "https://github.com/jerry73204/rust-lidar-utils"
repository = "https://github.com/jerry73204/rust-lidar-utils"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
failure = "^0.1.6"
serde = { version = "^1.0.104", features = ["derive"] }
serde_json = "^1.0.44"
serde_yaml = "^0.8.11"
serde-big-array = "^0.2.0"
chrono = "^0.4.10"
ndarray = "^0.13.0"
derivative = "^1.0.3"
itertools = "^0.8.2"
pcap = { version = "^0.7.0", optional = true }
uom = { version = "^0.26.0", features = ["u32", "u64", "u16", "si"] }
num-traits = "^0.2.10"
typenum = "^1.11.2"
generic-array = "^0.13.2"

[dev-dependencies]
log = "^0.4.8"
pretty_env_logger = "^0.3.1"
pcap = "^0.7.0"
toml = "^0.5.5"

[features]
with-pcap = ["pcap"]
ouster-api-test = []
ouster-test = []
velodyne-test = []
