[package]
name = "lidar-utils"
version = "0.3.1"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
description = "Utilities for Velodyne and Ouster LIDARs"
documentation = "https://docs.rs/lidar-utils/"
homepage = "https://github.com/jerry73204/rust-lidar-utils"
repository = "https://github.com/jerry73204/rust-lidar-utils"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
failure = "~0"
serde = { version = "~1", features = ["derive"] }
serde_json = "~1"
serde-big-array = "~0"
chrono = "~0"
log = "~0"
ndarray = "~0"
derivative = "~1"
regex = "~1"
itertools = "^0.8.2"
pcap = { version = "~0", optional = true }
pcd-rs = { version = "~0", optional = true }
clap = { version = "~2", features = ["yaml"], optional = true }
uom = { version = "^0.26.0", features = ["u32", "u64", "u16", "si"] }
num-traits = "^0.2.10"

[dev-dependencies]
pretty_env_logger = "~0"
pcap = "~0"
toml = "~0"

[features]
enable-pcap = ["pcap"]
ouster-api-test = []
ouster-test = []
velodyne-test = []
