[package]
name = "lidar-utils"
version = "0.5.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
description = "Utilities for Velodyne and Ouster LIDARs"
documentation = "https://docs.rs/lidar-utils/"
homepage = "https://github.com/jerry73204/rust-lidar-utils"
repository = "https://github.com/jerry73204/rust-lidar-utils"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
serde-big-array = "0.2"
chrono = "0.4"
ndarray = "0.13"
derivative = "1.0"
itertools = "0.8"
pcap = { version = "0.7", optional = true }
uom = { version = "0.26", features = ["u32", "u64", "u16", "si"] }
num-traits = "0.2"
typenum = "1.11"
generic-array = "0.13"

[dev-dependencies]
log = "0.4"
pretty_env_logger = "0.3"
pcap = "0.7"
toml = "0.5"

[features]
ouster-api-test = []
ouster-test = []
velodyne-test = []

[package.metadata.docs.rs]
features = ["pcap"]
no-default-features = true
