[package]
name = "velodyne-lidar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
serde_yaml = "0.8.23"
serde-big-array = "0.3.2"
chrono = "0.4.19"
derivative = "2.2.0"
itertools = "0.10.3"
num-traits = "0.2.14"
noisy_float = { version = "0.2.0", features = ["serde"] }
measurements = "0.11.0"
once_cell = "1.9.0"
strum = { version = "0.23.0", features = ["derive"] }
nmea = { version = "0.0.11", optional = true }
pcap = { version = "0.9.1", optional = true }
futures = { version = "0.3.21", optional = true }

[dev-dependencies]
log = "0.4.14"
pcap = "0.9.1"
toml = "0.5.8"

[features]
default = ["full"]
full = ["nmea", "async", "pcap"]
async = ["futures"]
